name: rockdot_framework
version: 0.5.1
description: Röckdöt Framewörk, based on a Spring framework implementation for StageXL.
dependencies:
  googleapis_auth: any
  googleapis: any
  rockdot_spring:
    git: https://github.com/blockforest/rockdot-spring