name: stagexl_rockdot
version: 0.5.0
description: StageXL port of Rockdot framework, based on Spring framework for StageXL.
dependencies:
  googleapis_auth: any
  googleapis: any
  stagexl_spring:
    git: https://github.com/blockforest/stagexl-spring